import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { FaEye, FaEyeSlash, FaCheck, FaTimes } from "react-icons/fa";
import IndakHamakaLogo from "../assets/FLIPinoNLogo.png";
import "./Register.css";
import { supabase } from "../supabasebaseClient"; // Make sure this path is correct

// Snackbar component for feedback
const Snackbar = ({ message, type, onClose }) => (
  <div
    className={`snackbar ${type}`}
    onClick={onClose}
    role="alert"
    aria-live="assertive"
  >
    {message}
  </div>
);

// Password Requirements component
const PasswordRequirements = ({ password, isVisible }) => {
  const requirements = [
    { key: 'length', text: '8-24 characters', check: password.length >= 8 && password.length <= 24 },
    { key: 'lowercase', text: 'One lowercase letter', check: /(?=.*[a-z])/.test(password) },
    { key: 'uppercase', text: 'One uppercase letter', check: /(?=.*[A-Z])/.test(password) },
    { key: 'number', text: 'One number', check: /(?=.*\d)/.test(password) },
    { key: 'special', text: 'One special character', check: /(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?`~])/.test(password) }
  ];

  if (!isVisible) return null;

  return (
    <div className="password-requirements">
      <div className="requirements-title">Password Requirements:</div>
      {requirements.map(req => (
        <div key={req.key} className={`requirement-item ${req.check ? 'valid' : 'invalid'}`}>
          <span className="requirement-icon">
            {req.check ? <FaCheck /> : <FaTimes />}
          </span>
          <span className="requirement-text">{req.text}</span>
        </div>
      ))}
    </div>
  );
};

// Privacy Modal component
const PrivacyModal = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="privacy-modal-overlay" onClick={onClose}>
      <div className="privacy-modal-content" onClick={e => e.stopPropagation()}>
        <div className="privacy-modal-header">
          <h2>Privacy Policy</h2>
          <button className="privacy-modal-close" onClick={onClose}>
            <FaTimes />
          </button>
        </div>
        <div className="privacy-modal-body">
          <div className="privacy-content">
            <h3>Privacy Policy</h3>
            <p className="last-updated"><strong>Last Updated: October 10, 2025</strong></p>
            
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            
            <h4>Interpretation and Definitions</h4>
            <p><strong>Interpretation</strong></p>
            <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            
            <p><strong>Definitions</strong></p>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to FLIPino</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Philippines</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>Website</strong> refers to FLIPino, accessible from https://web-cap-master.vercel.app/</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
            
            <h4>Collecting and Using Your Personal Data</h4>
            <p><strong>Types of Data Collected</strong></p>
            
            <p><strong>Personal Data</strong></p>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul>
              <li>Username</li>
              <li>Email address</li>
              <li>Date of Birth</li>
              <li>Gender (Optional)</li>
              <li>Usage Data</li>
            </ul>
            
            <p><strong>Usage Data</strong></p>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            
            <p><strong>Performance and Learning Data</strong></p>
            <p>When you use our dance learning features, we collect and store the following data to track your progress and improve your learning experience:</p>
            <ul>
              <li><strong>Dance Performance Metrics:</strong> Your scores, accuracy ratings, and completion status for each dance attempt</li>
              <li><strong>Practice History:</strong> Timestamps and frequency of your dance practice sessions</li>
              <li><strong>Figure-Specific Performance:</strong> Individual performance data for specific dance moves and figures</li>
              <li><strong>User Ratings and Feedback:</strong> Your ratings (0-5 scale) and feedback on dances and learning materials</li>
              <li><strong>Progress Analytics:</strong> Completion rates, improvement trends, and learning patterns</li>
              <li><strong>Video Processing Data (Mobile App):</strong> When you record yourself performing a dance on our mobile app, the video is temporarily uploaded to our server for motion comparison and analysis. This video is automatically deleted immediately after processing is complete and is never stored permanently.</li>
            </ul>
            <p>This performance data helps us provide personalized learning recommendations, track your progress over time, and improve our educational content.</p>
            
            <h4>Third-Party Services</h4>
            <p>We use the following third-party service providers to operate and improve our Service. These providers may have access to your Personal Data only to perform specific tasks on our behalf and are obligated not to disclose or use it for any other purpose:</p>
            <ul>
              <li><strong>Supabase:</strong> We use Supabase for user authentication, database management, and secure data storage. Supabase processes your account information, login credentials, and performance data. Supabase is GDPR and SOC 2 Type II compliant. Learn more at <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer">https://supabase.com/privacy</a></li>
              <li><strong>EmailJS:</strong> We use EmailJS to send transactional emails such as account verification, password resets, and important notifications. EmailJS processes your email address for this purpose. Learn more at <a href="https://www.emailjs.com/legal/privacy-policy/" target="_blank" rel="noopener noreferrer">https://www.emailjs.com/legal/privacy-policy/</a></li>
              <li><strong>Vercel:</strong> Our web application is hosted on Vercel's infrastructure. Vercel may collect usage logs and technical data necessary for hosting and performance monitoring. Learn more at <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">https://vercel.com/legal/privacy-policy</a></li>
            </ul>
            <p>By using our Service, you acknowledge and agree that your data may be transferred to and processed by these third-party service providers in accordance with their respective privacy policies.</p>
            
            <h4>Tracking Technologies and Cookies</h4>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:</p>
            <ul>
              <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
              <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages.</li>
            </ul>
            
            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
            <ul>
              <li><strong>Necessary / Essential Cookies:</strong> These Cookies are essential to provide You with services available through the Website.</li>
              <li><strong>Cookies Policy / Notice Acceptance Cookies:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</li>
              <li><strong>Functionality Cookies:</strong> These Cookies allow us to remember choices You make when You use the Website.</li>
            </ul>
            
            <h4>Use of Your Personal Data</h4>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
              <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li>To provide You with news, special offers, and general information about other goods, services and events.</li>
              <li>To manage Your requests: To attend and manage Your requests to Us.</li>
              <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale.</li>
            </ul>
            
            <h4>Retention of Your Personal Data</h4>
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
            
            <h4>Transfer of Your Personal Data</h4>
            <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
            
            <h4>Disclosure of Your Personal Data</h4>
            <p><strong>Business Transactions</strong></p>
            <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</p>
            
            <p><strong>Law enforcement</strong></p>
            <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law.</p>
            
            <h4>Security of Your Personal Data</h4>
            <p>The security of Your Personal Data is important to Us. We implement industry-standard security measures including:</p>
            <ul>
              <li><strong>Secure Authentication:</strong> Authentication and password management are handled through Supabase's secure infrastructure, which uses industry-standard encryption and hashing algorithms. Passwords are never stored in plain text.</li>
              <li><strong>Database Security:</strong> All Personal Data is stored securely using Supabase's GDPR-compliant and SOC 2 Type II certified infrastructure.</li>
              <li><strong>HTTPS Encryption:</strong> All data transmission between your device and our servers is encrypted using SSL/TLS protocols.</li>
              <li><strong>Access Controls:</strong> Strict access controls limit who can view or modify your Personal Data.</li>
            </ul>
            <p>However, remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect Your Personal Data, we cannot guarantee its absolute security.</p>
            
            <h4>Children's Privacy</h4>
            <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.</p>
            
            <h4>Links to Other Websites</h4>
            <p>Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit.</p>
            
            <h4>Changes to this Privacy Policy</h4>
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and update the "Last updated" date at the top of this Privacy Policy.</p>
            
            <h4>Contact Us</h4>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <p><strong>By email:</strong> flipinoteam@gmail.com</p>
            
            <p className="privacy-footer">
              <strong>By using FLIPino, you acknowledge that you have read and understood this Privacy Policy and agree to its terms.</strong>
            </p>
          </div>
        </div>
        <div className="privacy-modal-footer">
          <button className="privacy-modal-accept" onClick={onClose}>
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
};

// Terms Modal component
const TermsModal = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="terms-modal-overlay" onClick={onClose}>
      <div className="terms-modal-content" onClick={e => e.stopPropagation()}>
        <div className="terms-modal-header">
          <h2>Terms and Conditions</h2>
          <button className="terms-modal-close" onClick={onClose}>
            <FaTimes />
          </button>
        </div>
        <div className="terms-modal-body">
          <div className="terms-content">
            <h3>Terms of Service - FLIPino</h3>
            <p className="last-updated"><strong>Last Updated: October 10, 2025</strong></p>
            
            <h4>1. Acceptance of Terms</h4>
            <p>By accessing or using FLIPino ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.</p>
            
            <h4>2. Description of Service</h4>
            <p>FLIPino is an educational platform dedicated to Filipino traditional dance learning and cultural preservation. The Service provides:</p>
            <ul>
              <li>Dance tutorials and step-by-step instructions</li>
              <li>Performance tracking and progress analytics</li>
              <li>Cultural education resources</li>
            </ul>
            
            <h4>3. User Accounts and Registration</h4>
            <p><strong>3.1 Account Requirements</strong></p>
            <ul>
              <li>You must provide a valid Gmail address (@gmail.com)</li>
              <li>Username must be 6-16 characters long and unique</li>
              <li>Password must meet security requirements (8-24 characters with uppercase, lowercase, number, and special character)</li>
            </ul>
            
            <h4>4. Data Collection and Privacy</h4>
            <p><strong>4.1 Personal Information Collected</strong></p>
            <ul>
              <li>Username (6-16 characters, used as display name)</li>
              <li>Email address (Gmail accounts only)</li>
              <li>Date of Birth (to verify minimum age of 13)</li>
              <li>Gender (optional)</li>
              <li>Account creation date and status</li>
              <li>User role and permissions</li>
            </ul>
            
            <p><strong>4.2 Performance and Learning Data</strong></p>
            <ul>
              <li>Dance attempt scores and timestamps</li>
              <li>Figure-specific performance metrics</li>
              <li>Progress tracking and completion rates</li>
              <li>User feedback and ratings (0-5 scale)</li>
              <li>Learning analytics and preferences</li>
              <li><strong>Video recordings (Mobile App):</strong> Temporary video uploads for motion analysis, automatically deleted after processing</li>
            </ul>
            
            <p>For complete details on how we collect, use, and protect your data, please review our Privacy Policy.</p>
            
            <h4>5. Acceptable Use Policy</h4>
            <p><strong>5.1 Permitted Uses</strong></p>
            <ul>
              <li>Educational and cultural learning purposes</li>
              <li>Personal skill development in Filipino traditional dance</li>
              <li>Sharing knowledge and cultural appreciation</li>
            </ul>
            
            <p><strong>5.2 Prohibited Activities</strong></p>
            <ul>
              <li>Uploading false, misleading, or culturally insensitive content</li>
              <li>Attempting to gain unauthorized access to other user accounts</li>
              <li>Using the Service for commercial purposes without permission</li>
              <li>Harassment, bullying, or inappropriate behavior toward other users</li>
              <li>Violating intellectual property rights</li>
            </ul>
            
            <h4>6. Cultural Sensitivity and Respect</h4>
            <ul>
              <li>Content must respect Filipino cultural traditions</li>
              <li>Regional variations and interpretations are acknowledged</li>
              <li>Traditional knowledge is treated with appropriate reverence</li>
              <li>Primary goal is cultural preservation and education</li>
            </ul>
            
            <h4>7. Disclaimer and Limitation of Liability</h4>
            <p>The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. FLIPino does not guarantee:</p>
            <ul>
              <li>Uninterrupted or error-free service</li>
              <li>Accuracy of dance instruction or cultural information</li>
              <li>Achievement of specific learning outcomes</li>
            </ul>
            <p>FLIPino shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the Service.</p>
            
            <h4>8. Changes to These Terms</h4>
            <p>We reserve the right to modify these Terms at any time. When we make changes:</p>
            <ul>
              <li>We will update the "Last Updated" date at the top of this document</li>
              <li>Significant changes will be communicated via email</li>
              <li>Continued use of the Service after changes constitutes acceptance of the new Terms</li>
              <li>If you do not agree to the updated Terms, you must stop using the Service</li>
            </ul>
            
            <h4>9. Contact Us</h4>
            <p>If you have any questions about these Terms of Service, you can contact us:</p>
            <p><strong>By email:</strong> flipinoteam@gmail.com</p>
            
            <h4>10. Governing Law and Jurisdiction</h4>
            <p>These Terms of Service shall be governed by and construed in accordance with the laws of the Republic of the Philippines, without regard to its conflict of law provisions. We comply with the Data Privacy Act of 2012 (Republic Act No. 10173) and regulations enforced by the National Privacy Commission.</p>
            <p>Any disputes, claims, or legal proceedings arising from or related to your use of FLIPino shall be resolved exclusively in the competent courts of the Philippines. By using our Service, you consent to the jurisdiction and venue of such courts.</p>
            
            <p className="terms-footer">
              <strong>By using FLIPino, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.</strong>
            </p>
          </div>
        </div>
        <div className="terms-modal-footer">
          <button className="terms-modal-accept" onClick={onClose}>
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
};

const Register = () => {
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [dateOfBirth, setDateOfBirth] = useState("");
  const [gender, setGender] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [showPasswordRequirements, setShowPasswordRequirements] = useState(false);
  const [snackbar, setSnackbar] = useState({ message: "", type: "" });
  const [loading, setLoading] = useState(false);
  const [acceptTerms, setAcceptTerms] = useState(false);
  const [showTermsModal, setShowTermsModal] = useState(false);
  const [showPrivacyModal, setShowPrivacyModal] = useState(false);
  const navigate = useNavigate();

  const showSnackbar = (message, type) => {
    setSnackbar({ message, type });
    // Show error messages longer than success messages
    const timeout = type === "error" ? 5000 : 3000;
    setTimeout(() => setSnackbar({ message: "", type: "" }), timeout);
  };

  const validatePassword = (password) => {
    const requirements = [
      { check: password.length >= 8 && password.length <= 24, message: "Password must be between 8-24 characters long." },
      { check: /(?=.*[a-z])/.test(password), message: "Password must contain at least one lowercase letter." },
      { check: /(?=.*[A-Z])/.test(password), message: "Password must contain at least one uppercase letter." },
      { check: /(?=.*\d)/.test(password), message: "Password must contain at least one number." },
      { check: /(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?`~])/.test(password), message: "Password must contain at least one special character." }
    ];
    
    const failedRequirements = requirements.filter(req => !req.check);
    if (failedRequirements.length > 0) {
      return failedRequirements[0].message;
    }
    
    return null;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    // Terms and Conditions validation
    if (!acceptTerms) {
      showSnackbar("Please accept the Terms and Conditions and Privacy Policy to continue", "error");
      setLoading(false);
      return;
    }

    // Gmail validation
    if (!email.endsWith("@gmail.com")) {
      showSnackbar("Please use a Gmail address (@gmail.com)", "error");
      setLoading(false);
      return;
    }

    // Username validation: min 6, max 16
    if (username.length < 6 || username.length > 16) {
      showSnackbar("Username must be between 6 and 16 characters!", "error");
      setLoading(false);
      return;
    }

    // Date of Birth validation (minimum age 13)
    if (!dateOfBirth) {
      showSnackbar("Please enter your date of birth", "error");
      setLoading(false);
      return;
    }

    const birthDate = new Date(dateOfBirth);
    const today = new Date();
    const age = Math.floor((today - birthDate) / (365.25 * 24 * 60 * 60 * 1000));

    if (age < 13) {
      showSnackbar("You must be at least 13 years old to register", "error");
      setLoading(false);
      return;
    }

    if (age > 120) {
      showSnackbar("Please enter a valid date of birth", "error");
      setLoading(false);
      return;
    }

    // Gender validation
    if (!gender) {
      showSnackbar("Please select your gender", "error");
      setLoading(false);
      return;
    }

    // Password validation: min 8, max 24, with complexity requirements
    const passwordError = validatePassword(password);
    if (passwordError) {
      showSnackbar(passwordError, "error");
      setLoading(false);
      return;
    }

    if (password !== confirmPassword) {
      showSnackbar("Passwords do not match!", "error");
      setLoading(false);
      return;
    }

    try {
      // Step 1: Check if username already exists
      const { data: existingUser, error: checkError } = await supabase
        .from('users')
        .select('username')
        .eq('username', username)
        .single();

      if (checkError && checkError.code !== 'PGRST116') { // PGRST116 = no rows found (which is good)
        console.error("Error checking username:", checkError);
        showSnackbar("Error checking username availability. Please try again.", "error");
        setLoading(false);
        return;
      }

      if (existingUser) {
        showSnackbar("This username is already taken. Please choose a different username.", "error");
        setLoading(false);
        return;
      }

      // Step 2: Sign up in Supabase Auth and set display_name
      const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
        email,
        password,
        options: {
          data: {
            display_name: username, // save username in Auth metadata
          },
        },
      });

      if (signUpError) {
        console.error("Supabase signUp error:", signUpError);
        
        // Handle specific error cases with user-friendly messages
        let errorMessage = "Registration failed. Please try again.";
        
        if (signUpError.message?.toLowerCase().includes("email")) {
          if (signUpError.message.toLowerCase().includes("already") || 
              signUpError.message.toLowerCase().includes("registered") ||
              signUpError.message.toLowerCase().includes("exists")) {
            errorMessage = "An account with this email already exists. Please use a different email or try logging in.";
          } else if (signUpError.message.toLowerCase().includes("invalid")) {
            errorMessage = "Please enter a valid email address.";
          }
        } else if (signUpError.message?.toLowerCase().includes("password")) {
          errorMessage = "Password does not meet requirements. Please check and try again.";
        } else if (signUpError.message?.toLowerCase().includes("network") || 
                   signUpError.message?.toLowerCase().includes("connection")) {
          errorMessage = "Network error. Please check your connection and try again.";
        }
        
        showSnackbar(errorMessage, "error");
        setLoading(false);
        return;
      }

      // Step 3: Insert into your custom users table (mirror username from Auth)
      if (signUpData?.user?.id) {
        const birthDate = new Date(dateOfBirth);
        const today = new Date();
        const calculatedAge = Math.floor((today - birthDate) / (365.25 * 24 * 60 * 60 * 1000));

        const { error: dbError } = await supabase.from("users").insert([
          {
            id: signUpData.user.id, // link to auth.users.id
            username: signUpData.user.user_metadata.display_name, // always mirrors Auth
            email,
            age: calculatedAge,
            gender,
            role: "user", // default role
            status: "Enabled", // default status - matches UserManagement system
          },
        ]);

        if (dbError) {
          console.error("Insert into users failed:", dbError.message);
          
          // Handle specific database errors with user-friendly messages
          let errorMessage = "Failed to create user profile. Please try again.";
          
          if (dbError.message?.toLowerCase().includes("duplicate key") || 
              dbError.message?.toLowerCase().includes("unique constraint")) {
            if (dbError.message.toLowerCase().includes("email")) {
              errorMessage = "An account with this email already exists. Please use a different email or try logging in.";
            } else if (dbError.message.toLowerCase().includes("username")) {
              errorMessage = "This username is already taken. Please choose a different username.";
            } else {
              errorMessage = "An account with these details already exists. Please try different information.";
            }
          } else if (dbError.message?.toLowerCase().includes("network") || 
                     dbError.message?.toLowerCase().includes("connection")) {
            errorMessage = "Network error. Please check your connection and try again.";
          }
          
          showSnackbar(errorMessage, "error");
          setLoading(false);
          return;
        }
      }

      showSnackbar(
        "Registration successful! Please check your email to confirm your account.",
        "success"
      );
      setTimeout(() => navigate("/login"), 3000);
    } catch (err) {
      showSnackbar(`Unexpected error: ${err.message}`, "error");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="register-container">
      <div className="register-header">
        <div className="register-logo">
          <img src={IndakHamakaLogo} alt="FLIPino" className="logo-image" />
          <span className="logo-text">FLIPino</span>
        </div>
      </div>

      <div className="register-content">
        <div className="register-box">
          <h1 className="register-title">Hello!</h1>
          <p className="register-subtitle">Let's Register Your Account</p>

          <div className="form-box">
            <form onSubmit={handleSubmit} className="register-form">
              <div className="input-group">
                <label className="input-label">Username</label>
                <input
                  type="text"
                  placeholder="Enter your username"
                  className="register-input"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                />
              </div>

              <div className="input-group">
                <label className="input-label">Email</label>
                <input
                  type="email"
                  placeholder="Enter your email"
                  className="register-input"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>

              {/* Age and Gender Side by Side */}
              <div className="input-group-row">
                <div className="input-group input-group-half">
                  <label className="input-label">Date of Birth</label>
                  <input
                    type="date"
                    className="register-input"
                    value={dateOfBirth}
                    onChange={(e) => setDateOfBirth(e.target.value)}
                    required
                    max={new Date(new Date().setFullYear(new Date().getFullYear() - 13)).toISOString().split('T')[0]}
                  />
                </div>

                <div className="input-group input-group-half">
                  <label className="input-label">Gender</label>
                  <select
                    className="register-input"
                    value={gender}
                    onChange={(e) => setGender(e.target.value)}
                    required
                  >
                    <option value="">Gender</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                    <option value="Prefer not to say">Prefer not to say</option>
                  </select>
                </div>
              </div>

              <div className="input-group">
                <label className="input-label">Password</label>
                <div className="password-input-container">
                  <input
                    type={showPassword ? "text" : "password"}
                    placeholder="Enter your password"
                    className="register-input password-input"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    onFocus={() => setShowPasswordRequirements(true)}
                    onBlur={() => setTimeout(() => setShowPasswordRequirements(false), 150)}
                    required
                    minLength={8}
                    maxLength={24}
                    style={{ paddingRight: "40px" }}
                  />
                  <span
                    onClick={() => setShowPassword(!showPassword)}
                    style={{
                      position: "absolute",
                      top: "50%",
                      right: "15px",
                      transform: "translateY(-50%)",
                      cursor: "pointer",
                      color: "#555",
                      fontSize: "18px",
                    }}
                  >
                    {showPassword ? <FaEyeSlash /> : <FaEye />}
                  </span>
                </div>
                <PasswordRequirements 
                  password={password} 
                  isVisible={showPasswordRequirements} 
                />
              </div>

              <div className="input-group">
                <label className="input-label">Confirm Password</label>
                <div className="password-input-container">
                  <input
                    type={showConfirmPassword ? "text" : "password"}
                    placeholder="Confirm your password"
                    className="register-input password-input"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    required
                    minLength={8}
                    maxLength={24}
                    style={{ paddingRight: "40px" }}
                  />
                  <span
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    style={{
                      position: "absolute",
                      top: "50%",
                      right: "15px",
                      transform: "translateY(-50%)",
                      cursor: "pointer",
                      color: "#555",
                      fontSize: "18px",
                    }}
                  >
                    {showConfirmPassword ? <FaEyeSlash /> : <FaEye />}
                  </span>
                </div>
              </div>

              <div className="terms-checkbox-container">
                <div className="terms-checkbox-wrapper">
                  <label className="terms-checkbox-label-only">
                    <input
                      type="checkbox"
                      checked={acceptTerms}
                      onChange={(e) => setAcceptTerms(e.target.checked)}
                      className="terms-checkbox"
                    />
                    <span className="checkbox-custom"></span>
                  </label>
                  <div className="terms-text-wrapper">
                    I have read and agree to the{" "}
                    <span
                      className="terms-link"
                      onClick={() => setShowTermsModal(true)}
                    >
                      Terms and Conditions
                    </span>
                    {" "}and{" "}
                    <span
                      className="privacy-link"
                      onClick={() => setShowPrivacyModal(true)}
                    >
                      Privacy Policy
                    </span>
                  </div>
                </div>
              </div>

              <button type="submit" className="register-button" disabled={loading || !acceptTerms}>
                {loading ? "Registering..." : "Register"}
              </button>
            </form>

            <p className="register-footer">
              Already have an account?{" "}
              <span onClick={() => navigate("/login")} className="register-link">
                Login
              </span>
            </p>
          </div>
        </div>
      </div>
      {snackbar.message && (
        <Snackbar
          message={snackbar.message}
          type={snackbar.type}
          onClose={() => setSnackbar({ message: "", type: "" })}
        />
      )}
      
      <TermsModal
        isOpen={showTermsModal}
        onClose={() => setShowTermsModal(false)}
      />
      
      <PrivacyModal
        isOpen={showPrivacyModal}
        onClose={() => setShowPrivacyModal(false)}
      />
    </div>
  );
};

export default Register;
